FROM golang:alpine


RUN apk add git


RUN go get github.com/googollee/go-socket.io
RUN go get github.com/lib/pq
RUN go get github.com/NaySoftware/go-fcm


COPY ./main.go .


RUN go build main.go

EXPOSE 7000

CMD ./main