FROM golang:alpine

RUN apk add git


RUN go get github.com/gorilla/mux
RUN go get github.com/lib/pq

WORKDIR /usr/Wallet-Transaction

COPY . .


RUN go build .

EXPOSE 10000

CMD ./Wallet-Transaction