FROM golang:alpine

RUN apk add git


RUN go get github.com/gorilla/mux
RUN go get github.com/lib/pq
RUN go get github.com/dgrijalva/jwt-go
RUN go get github.com/NaySoftware/go-fcm



WORKDIR /usr/Wallet-Transaction

COPY . .


RUN go build .

EXPOSE 10000

CMD ./Wallet-Transaction